export const MINER_CONSTANTS = {
  DEFAULT_ITERATIONS: 16,
  DEFAULT_WORKGROUP_SIZE: 256,
  DEFAULT_OUTPUT_U32_LENGTH: 2,
  PARTIAL_HEADER_U32_LENGTH: 21,
  TARGET_U32_LENGTH: 8,
  PARAMS_U32_LENGTH: 4,
  FOUND_INDEX: 0,
  NONCE_INDEX: 1,
  DEFAULT_RPC_POLL_MS: 3000,
  DEFAULT_HASHRATE_WINDOW_MS: 5000,
  DEFAULT_KERNEL_SIZE: 1 << 23,
} as const
